### ISSUE TITLE
Fleece support for Java 

### ISSUE THREAD

**Issue by pkjvit** [couchbaselabs/fleece#35]
Recently, I have created [cblite-viewer](https://github.com/pkjvit/couchbase-lite-android-viewer) for Android apps to debug database and query on the same.

Now, I am creating [Android-data-debugger](https://github.com/pkjvit/Android-Data-Debugger) a generic tool for all sqlite/cblite databases for debugging. 
But to support cblite 2.0, I am stuck in fleece code to decode it in JSON. 

Can you please help in this either I create different sdk to support cblite 2.0 or provide support in the generic one through fleece java support?

How can I use Fleece in JAVA to convert fleece code to JSON and vice-versa?

**Comment by snej** [comment]
The Java/JNI support code in couchbase-lite-core includes glue for accessing Fleece. I'm not sure exactly how it works because I haven't looked at it myself.

Of course it's also possible to implement Fleece in pure Java. A Fleece `Value` would be a Java object whose members are a byte array and an offset into that array.
